### ISSUE TITLE
missing argument error

### ISSUE THREAD

**Issue by aafaqin** [zigiiprens/OpenImageDownloader#1]
I fired this command python main.py downloader --version v6 --classes Handgun Shotgun Rifle --type_csv train

This is the error am getting

Traceback (most recent call last):
  File "main.py", line 36, in <module>
    bounding_boxes_images(args, DEFAULT_OID_DIR)
  File "/media/aafaq/work_drive/datasets/openimageguns/OpenImageDownloader/modules/bounding_boxes.py", line 46, in bounding_boxes_images
    mkdirs(dataset_dir, csv_dir, args.classes, args.type_csv)
TypeError: mkdirs() missing 1 required positional argument: 'type_csv'
(NNs) 
![Screenshot from 2020-09-28 09-49-36](https://user-images.githubusercontent.com/22724087/94390315-f2b6dc80-016f-11eb-9932-2227261f473d.png)

**Comment by SheldonWBM** [comment]
I am having the same issue. I tried `--type_csv train` and `--type_csv 'train'`. Also tried with `test`
